### ISSUE TITLE
Problem with webpack

### ISSUE THREAD

**Issue by nachocs** [jfangrad/react-dropdown-aria#10]
Hello. Thanks very much for the library, is very useful.
I found a problem when trying to make my app work for ie11, using webpack and babel, it happened that 'react-dropdown-aria' was not transpiled properly, leaving 'const' and default values (like {selected = false}, that broke ie11. 
Investigating this I found that your distribution is in ES6 and that causes these problems.
Maybe better to make the dist for ES5?
I solved the problem in my end just making a copy of the library, then babel with webpack transpiles it, but I suppose the best way for the library itself would be to make it more compatible.
Thanks for your help.

**Comment by sachinantony** [comment]
@jfangrad I am facing the same issue in chrome and firefox as well.
@nachocs Did you take a clone of the project and build it in a different way? Can you please explain what you did?

**Comment by jfangrad** [comment]
@nachocs @sachinantony without your build config files it is hard for me to help out as I can't recreate the issues myself. I would be happy to help if you can provide me with that information!

**Comment by nachocs** [comment]
I just cloned the library and used internally in the project, and it works fine like that.
I tried a lot of possible configurations on webpack with no luck. All rest of libraries have no problem. I only found it out when testing on IE11
Here you have my webpack config:
`import path from 'path';

import webpack from 'webpack';
import merge from 'webpack-merge';
import CleanWebpackPlugin from 'clean-webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
import TerserJSPlugin from 'terser-webpack-plugin';
import OptimizeCSSAssetsPlugin from 'optimize-css-assets-webpack-plugin';

const sassPaths = ['node_modules'];

// References the application's root path
const ROOT_PATH = path.resolve(__dirname);

// Sets the variable as either development or production
const ENV = process.env.NODE_ENV || 'development';

// Sets appEnv so the the header component will point to the search app on either Dev or Prod
const appEnv = process.env.APP_ENV ? process.env.APP_ENV : 'production';

// Holds the common settings for any environment
const commonSettings = {
  // path.resolve - resolves to an absolute path
  // This is the path and file of our top level
  // React App that is to be rendered.
  entry: ['@babel/polyfill', path.resolve(ROOT_PATH, 'src/client/App.jsx')],
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  output: {
    // Sets the output path to ROOT_PATH/dist
    path: path.resolve(ROOT_PATH, 'dist'),
    // Sets the name of the bundled application files
    // Additionally we can isolate vendor files as well
    filename: 'bundle.js',
  },
  plugins: [
    // Cleans the Dist folder after every build.
    // Alternately, we can run rm -rf dist/ as
    // part of the package.json scripts.
    new CleanWebpackPlugin(),
    new MiniCssExtractPlugin({
      filename: 'styles.css',
    }),
    new webpack.DefinePlugin({
      loadA11y: process.env.loadA11y || false,
      appEnv: JSON.stringify(appEnv),
    }),
  ],
};

/**
 * DEVELOPMENT ENVIRONMENT CONFIG
 * ------------------------------
 * Uses the webpack-merge plugin to merge
 * the common app configuration with the
 * additional development specific settings.
 *
 */
// Need to configure webpack-dev-server and hot-reload
// module correctly.
if (ENV === 'development') {
  module.exports = merge(commonSettings, {
    mode: 'development',
    devtool: 'inline-source-map',
    entry: {
      app: [
        '@babel/polyfill',
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        path.resolve(ROOT_PATH, 'src/client/App.jsx'),
      ],
    },
    output: {
      publicPath: 'http://localhost:3000/',
    },
    plugins: [
      new MiniCssExtractPlugin({
        filename: 'styles.css',
      }),
      new webpack.HotModuleReplacementPlugin(),
      new webpack.DefinePlugin({
        'process.env': {
          APP_ENV: JSON.stringify('development'),
        },
      }),
    ],
    resolve: {
      modules: ['node_modules'],
      extensions: ['.js', '.jsx', '.scss'],
    },
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /(node_modules|bower_components)/,
          use: 'babel-loader',
        },
        {
          test: /\.scss?$/,
          use: ['style-loader', 'css-loader', `sass-loader?includePaths=${sassPaths}`],
          include: path.resolve(ROOT_PATH, 'src'),
        },
        {
          test: /\.(gif|png|jp?g|svg)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[ext]',
                outputPath: 'img/',
              },
            },
          ],
        },
        {
          test: /\.(ttf|eot|woff(2)?)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[ext]',
                outputPath: 'fonts/',
              },
            },
          ],
        },
      ],
    },
  });
}

/**
 * PRODUCTION ENVIRONMENT CONFIG
 * ------------------------------
 * Uses the webpack-merge plugin to merge
 * the common app configuration with the
 * additional production specific settings.
 *
 */
if (ENV === 'production') {
  module.exports = merge(commonSettings, {
    mode: 'production',
    plugins: [
      new MiniCssExtractPlugin({
        filename: 'styles.css',
      }),
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify('production'),
          APP_ENV: JSON.stringify(appEnv),
        },
      }),
    ],
    optimization: {
      minimizer: [new TerserJSPlugin({}), new OptimizeCSSAssetsPlugin({})],
    },
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /(node_modules|bower_components)/,
          use: 'babel-loader',
        },
        {
          test: /\.scss?$/,
          use: [MiniCssExtractPlugin.loader, 'css-loader', `sass-loader?includePaths=${sassPaths}`],
          include: path.resolve(ROOT_PATH, 'src'),
        },
        {
          test: /\.(gif|png|jp?g|svg)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[ext]',
                outputPath: 'img/',
              },
            },
          ],
        },
        {
          test: /\.(ttf|eot|woff(2)?)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[ext]',
                outputPath: 'fonts/',
              },
            },
          ],
        },
      ],
    },
  });
}
`

**Comment by jfangrad** [comment]
@nachocs @sachinantony I have released a new version ```1.3.1``` of the library. I got it to work in one of my own projects with IE11 so let me know if the updated version works for you guys

**Comment by nachocs** [comment]
Thank you very much

**Comment by jfangrad** [comment]
Closing issue now that build has changed to support ie11. Reopen if any issues.
