### ISSUE TITLE
demo 

### ISSUE THREAD

**Issue by isaiahr** [jfangrad/react-dropdown-aria#27]
the "Custom Option Render Function" thingy is broken i think?
it doesnt right align at all and i think its supposed to??? ? ?? ???? ?? ?  ? ? 

also elm is a language not a framework. (i think)

**Comment by jfangrad** [comment]
Thanks for the heads up! A bunch of the demos are in a bad state right now since the latest changes. I plan on going through and updating them soon.

**Comment by jfangrad** [comment]
It should be good now
