### ISSUE TITLE
Types aren't published with dist

### ISSUE THREAD

**Issue by devanfarrell** [jfangrad/react-dropdown-aria#36]
Types seem to have been skipped in the packaging step. Soft suggestion to consider TSDX for simplified packaging and rollup.

V2.0.3

**Comment by jfangrad** [comment]
Thanks for the heads up! Seems rollup isn't generating a `d.ts` file for `utils/types.ts` for some reason.

A fix is deployed at v2.0.4

I'll take a look at that TSDX lib and see if that can help as well.
