### ISSUE TITLE
The produced HTML is missing <li>:s

### ISSUE THREAD

**Issue by venlahy** [jfangrad/react-dropdown-aria#39]
The HTML that the dropdown produces in the page https://jfangrad.github.io/react-dropdown-aria/ is wrong: The HTML is in the form `<ul><div></div></ul>`, although it should be like this: `<ul><li></li></ul>`.

**Comment by jfangrad** [comment]
Changed in v2.0.6. The `ul` changed to a `div`. I don't think I should have been using `ul`.
