### ISSUE TITLE
Custom DropdownWrapper styling's dropdownFocused stays incorrectly true in Chrome after select and navigate away

### ISSUE THREAD

**Issue by venlahy** [jfangrad/react-dropdown-aria#41]
I made custom styling for DropdownWrapper like this:

```
DropdownWrapper: (base, { dropdownFocused }) => ({
    ...base,

    borderColor: dropdownFocused ? 'orange' : 'yellow'
}),
```

The dropdown should have orange borders when focused, and yellow borders, when not. But in Chrome, if I change the selected option in the dropdown and navigate away, the border stays orange, although it should be yellow. In Firefox, there is not a problem.

Is there a fix to this problem?

**Comment by jfangrad** [comment]
Hey, @venlahy I was not able to reproduce this on chrome. Could you provide a code sandbox with the issue?

**Comment by jfangrad** [comment]
Closing due to no response. Can reopen if the issue can be reproduced.
